insert into song (version, id, title, artist, genres) values (0,1, 'tincidunt ante vel ipsum praesent', 'Trina Ghilardini', '(no genress listed)');
insert into song (version, id, title, artist, genres) values (0,2, 'a suscipit nulla elit ac nulla sed vel enim', 'Camey Bunn', 'Drama|Fantasy|Musical|Romance');
insert into song (version, id, title, artist, genres) values (0,3, 'condimentum neque sapien placerat ante', 'Mickie Naish', 'Drama');
insert into song (version, id, title, artist, genres) values (0,4, 'in quam fringilla rhoncus mauris enim leo', 'Durward Taveriner', 'Drama');
insert into song (version, id, title, artist, genres) values (0,5, 'in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', 'Otha Scimone', 'Romance|Western');
insert into song (version, id, title, artist, genres) values (0,6, 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar', 'Mamie Addionizio', 'Comedy|Musical|Romance');
insert into song (version, id, title, artist, genres) values (0,7, 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum', 'Dougie Varian', 'Comedy|Romance');
insert into song (version, id, title, artist, genres) values (0,8, 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec', 'Anet Kemwall', 'Action|Horror|Sci-Fi');
insert into song (version, id, title, artist, genres) values (0,9, 'non quam nec dui luctus rutrum nulla tellus in sagittis dui', 'Raffarty Worthington', 'Drama|War');
insert into song (version, id, title, artist, genres) values (0,10, 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', 'Erskine Corrin', 'Comedy|Drama');
insert into song (version, id, title, artist, genres) values (0,11, 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', 'Major Magowan', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,12, 'at nibh in hac habitasse platea dictumst aliquam', 'Rafaela Chiplin', 'Drama');
insert into song (version, id, title, artist, genres) values (0,13, 'varius ut blandit non interdum in ante vestibulum ante', 'Cleve Carstairs', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,14, 'nisl nunc rhoncus dui vel', 'Maximo Wallicker', 'Drama|Romance');
insert into song (version, id, title, artist, genres) values (0,15, 'pharetra magna ac consequat metus sapien', 'Freeland McKean', 'Drama');
insert into song (version, id, title, artist, genres) values (0,16, 'faucibus orci luctus et ultrices posuere', 'Judi Pes', 'Thriller');
insert into song (version, id, title, artist, genres) values (0,17, 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et', 'Robinet Elphick', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,18, 'congue eget semper rutrum nulla nunc purus phasellus in felis', 'Elton Savell', 'Comedy|Drama');
insert into song (version, id, title, artist, genres) values (0,19, 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', 'Antoinette Goodanew', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,20, 'donec ut mauris eget massa', 'Olav Duncanson', 'Crime|Mystery|Romance|Thriller');
insert into song (version, id, title, artist, genres) values (0,21, 'nulla ut erat id mauris vulputate elementum nullam varius nulla', 'Lyle Goodwin', 'Action|Children|Comedy|Fantasy|Sci-Fi');
insert into song (version, id, title, artist, genres) values (0,22, 'diam erat fermentum justo nec condimentum', 'Derrek Biagini', 'Drama');
insert into song (version, id, title, artist, genres) values (0,23, 'bibendum morbi non quam nec dui luctus rutrum nulla', 'Juana Sultana', 'Drama|Romance|Western');
insert into song (version, id, title, artist, genres) values (0,24, 'in quis justo maecenas rhoncus aliquam lacus morbi quis tortor', 'Andres Sivier', 'Drama|Romance');
insert into song (version, id, title, artist, genres) values (0,25, 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', 'Willy Dubois', 'War');
insert into song (version, id, title, artist, genres) values (0,26, 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', 'Lorette Heinicke', 'Action|Adventure|Comedy');
insert into song (version, id, title, artist, genres) values (0,27, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', 'Carolan Kippins', 'Comedy|Romance');
insert into song (version, id, title, artist, genres) values (0,28, 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer', 'Inger Whanstall', 'Drama');
insert into song (version, id, title, artist, genres) values (0,29, 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit', 'Marleen Sivills', 'Action|Adventure|Drama');
insert into song (version, id, title, artist, genres) values (0,30, 'a suscipit nulla elit ac nulla sed vel enim sit amet', 'Rurik Castanaga', 'Drama');
insert into song (version, id, title, artist, genres) values (0,31, 'pede venenatis non sodales sed tincidunt eu felis', 'Darn MacMeanma', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,32, 'in blandit ultrices enim lorem ipsum', 'Aurthur Osgordby', 'Comedy|Drama|Romance');
insert into song (version, id, title, artist, genres) values (0,33, 'eu magna vulputate luctus cum sociis natoque', 'Ddene Scrace', 'Horror');
insert into song (version, id, title, artist, genres) values (0,34, 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui', 'Angeline Westmoreland', 'Horror|Mystery|Sci-Fi');
insert into song (version, id, title, artist, genres) values (0,35, 'in purus eu magna vulputate luctus cum sociis natoque penatibus', 'Kelley Fosdyke', 'Comedy|Drama|Romance');
insert into song (version, id, title, artist, genres) values (0,36, 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem', 'Bettye Brandts', 'Western');
insert into song (version, id, title, artist, genres) values (0,37, 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit', 'Morly Winchcomb', 'Crime|Drama|Thriller');
insert into song (version, id, title, artist, genres) values (0,38, 'enim leo rhoncus sed vestibulum sit amet', 'Steffane Portigall', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,39, 'varius nulla facilisi cras non velit', 'Frans Andreuzzi', 'Drama');
insert into song (version, id, title, artist, genres) values (0,40, 'duis consequat dui nec nisi volutpat eleifend donec', 'Adolpho Keaton', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,41, 'donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut', 'Ross Davinet', 'Comedy|Drama|War');
insert into song (version, id, title, artist, genres) values (0,42, 'phasellus in felis donec semper sapien a libero nam dui', 'Sig Vize', 'Drama|Horror');
insert into song (version, id, title, artist, genres) values (0,43, 'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 'Elwood Cookes', 'Action|Drama|War');
insert into song (version, id, title, artist, genres) values (0,44, 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum', 'Rycca Tilte', 'Comedy');
insert into song (version, id, title, artist, genres) values (0,45, 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 'Valaree Tupie', 'Drama');
insert into song (version, id, title, artist, genres) values (0,46, 'quisque ut erat curabitur gravida nisi at', 'Marlon Danbi', 'Comedy|Drama|Romance');
insert into song (version, id, title, artist, genres) values (0,47, 'mauris lacinia sapien quis libero nullam sit amet turpis elementum', 'Drusi Corps', 'Drama');
insert into song (version, id, title, artist, genres) values (0,48, 'nec sem duis aliquam convallis nunc proin at turpis', 'Andriana Symmers', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,49, 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis', 'Niki Gosneye', 'Documentary|Drama');
insert into song (version, id, title, artist, genres) values (0,50, 'eu interdum eu tincidunt in leo maecenas pulvinar lobortis', 'Madelon Simants', 'Drama|Romance');
insert into song (version, id, title, artist, genres) values (0,51, 'montes nascetur ridiculus mus etiam vel', 'Westleigh Sallis', 'Comedy|Romance');
insert into song (version, id, title, artist, genres) values (0,52, 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', 'Dev Sherington', 'Comedy|Romance');
insert into song (version, id, title, artist, genres) values (0,53, 'felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam', 'Allissa Sodory', 'Comedy|Drama');
insert into song (version, id, title, artist, genres) values (0,54, 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 'Deanna Sprowle', 'Mystery|Thriller');
insert into song (version, id, title, artist, genres) values (0,55, 'cum sociis natoque penatibus et magnis', 'Thekla Boyd', 'Drama');
insert into song (version, id, title, artist, genres) values (0,56, 'enim blandit mi in porttitor pede justo eu massa', 'Caleb Mingay', 'Drama');
insert into song (version, id, title, artist, genres) values (0,57, 'massa tempor convallis nulla neque libero convallis eget eleifend luctus', 'Francyne McEllen', 'Drama');
insert into song (version, id, title, artist, genres) values (0,58, 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus', 'Thekla Doley', 'Comedy|Horror|Musical');
insert into song (version, id, title, artist, genres) values (0,59, 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit', 'Bobbee Kubec', 'Action|Drama|Sci-Fi|Thriller');
insert into song (version, id, title, artist, genres) values (0,60, 'orci vehicula condimentum curabitur in libero ut massa volutpat convallis', 'Upton Lapre', 'Adventure|Animation|Children|Comedy');
insert into song (version, id, title, artist, genres) values (0,61, 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 'Deanna Jaime', 'Crime|Drama|Thriller');
insert into song (version, id, title, artist, genres) values (0,62, 'sed tristique in tempus sit amet sem fusce consequat', 'Mike Kalinsky', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,63, 'in eleifend quam a odio in hac habitasse platea', 'Mab Gehrts', 'Action|Thriller');
insert into song (version, id, title, artist, genres) values (0,64, 'augue aliquam erat volutpat in congue etiam justo etiam', 'Tomaso Cutteridge', 'Drama');
insert into song (version, id, title, artist, genres) values (0,65, 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur', 'Tansy Maydwell', 'Drama');
insert into song (version, id, title, artist, genres) values (0,66, 'pede malesuada in imperdiet et commodo vulputate justo in blandit', 'Etty Slinger', 'Comedy');
insert into song (version, id, title, artist, genres) values (0,67, 'fusce congue diam id ornare imperdiet sapien urna pretium', 'Jillana Wilcocks', 'Drama');
insert into song (version, id, title, artist, genres) values (0,68, 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 'Stormi Fricke', 'Comedy|Drama|Romance');
insert into song (version, id, title, artist, genres) values (0,69, 'ultrices enim lorem ipsum dolor', 'Laural Enrich', 'Comedy');
insert into song (version, id, title, artist, genres) values (0,70, 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', 'Andree Sulman', 'Drama|Mystery|Thriller');
insert into song (version, id, title, artist, genres) values (0,71, 'sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac', 'Yorke Rahl', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,72, 'odio elementum eu interdum eu tincidunt', 'Ker Whitewood', 'Drama');
insert into song (version, id, title, artist, genres) values (0,73, 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate', 'Margaret Castagne', 'Thriller');
insert into song (version, id, title, artist, genres) values (0,74, 'nec dui luctus rutrum nulla', 'Ange Richold', 'Drama');
insert into song (version, id, title, artist, genres) values (0,75, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 'Agosto Blowfield', 'Musical');
insert into song (version, id, title, artist, genres) values (0,76, 'sapien non mi integer ac neque duis', 'Karol Kenney', '(no genress listed)');
insert into song (version, id, title, artist, genres) values (0,77, 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 'Michelina Chavey', 'Action|Adventure|Crime|Western');
insert into song (version, id, title, artist, genres) values (0,79, 'curae duis faucibus accumsan odio', 'Thorvald Trousdell', 'Drama');
insert into song (version, id, title, artist, genres) values (0,80, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti', 'Ros Platfoot', 'Drama');
insert into song (version, id, title, artist, genres) values (0,81, 'quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede', 'Patty Eccleshall', 'Horror|Sci-Fi|Thriller');
insert into song (version, id, title, artist, genres) values (0,82, 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien', 'Bentlee Barns', 'Drama');
insert into song (version, id, title, artist, genres) values (0,83, 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 'Mohandas Shilling', 'Drama');
insert into song (version, id, title, artist, genres) values (0,84, 'aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque', 'Shalne Strippel', 'Romance');
insert into song (version, id, title, artist, genres) values (0,85, 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet', 'Rich Ticic', 'Comedy|Drama|Mystery|Thriller');
insert into song (version, id, title, artist, genres) values (0,86, 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris', 'Jeannie Crookston', 'Action|Comedy|Horror|Sci-Fi|Thriller|Western');
insert into song (version, id, title, artist, genres) values (0,87, 'porttitor lacus at turpis donec posuere metus vitae ipsum', 'Patten Paladino', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,88, 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie', 'Vladimir Pagin', 'Drama');
insert into song (version, id, title, artist, genres) values (0,89, 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', 'Niki Dy', 'Animation');
insert into song (version, id, title, artist, genres) values (0,90, 'urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit', 'Courtney Szanto', 'Action|Sci-Fi|Thriller|Western|IMAX');
insert into song (version, id, title, artist, genres) values (0,91, 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis', 'Briano Seward', 'Documentary|Drama');
insert into song (version, id, title, artist, genres) values (0,92, 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea', 'Gilbertine Syratt', 'Comedy|Fantasy|Romance');
insert into song (version, id, title, artist, genres) values (0,93, 'vestibulum rutrum rutrum neque aenean', 'Bobbie Lowbridge', 'Horror');
insert into song (version, id, title, artist, genres) values (0,94, 'nunc proin at turpis a', 'Helenelizabeth Fairbrass', 'Comedy|Crime|Horror');
insert into song (version, id, title, artist, genres) values (0,95, 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis', 'Heda Hinrichsen', 'Comedy');
insert into song (version, id, title, artist, genres) values (0,96, 'sed magna at nunc commodo placerat praesent blandit nam', 'Westleigh Junkinson', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,97, 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 'Ertha Bedminster', 'Action|Drama|War');
insert into song (version, id, title, artist, genres) values (0,98, 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget', 'Sonni Tresler', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,99, 'etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla', 'Michaella Rebeiro', 'Comedy|Drama|Horror|Sci-Fi|Thriller');
insert into song (version, id, title, artist, genres) values (0,100, 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum', 'Talbert Mosdall', 'Children|Drama');
insert into song (version, id, title, artist, genres) values (0,101, 'felis ut at dolor quis odio consequat varius integer', 'Cindelyn McBeth', 'Documentary|War');
insert into song (version, id, title, artist, genres) values (0,102, 'tempus sit amet sem fusce consequat nulla nisl', 'Hernando Meharry', 'Comedy');
insert into song (version, id, title, artist, genres) values (0,103, 'quis libero nullam sit amet turpis', 'Jerri Cristobal', 'Adventure|Animation|Children|Comedy|Fantasy|Romance');
insert into song (version, id, title, artist, genres) values (0,104, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam', 'Xylina Klaff', 'Comedy');
insert into song (version, id, title, artist, genres) values (0,105, 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 'Flora Cotta', 'Comedy');
insert into song (version, id, title, artist, genres) values (0,106, 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 'Nadya Lyston', 'Drama');
insert into song (version, id, title, artist, genres) values (0,107, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 'Pennie MacGovern', 'Documentary');
insert into song (version, id, title, artist, genres) values (0,108, 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 'Nikola Drache', 'Drama');
insert into song (version, id, title, artist, genres) values (0,109, 'penatibus et magnis dis parturient montes nascetur ridiculus', 'Birk Aylwin', '(no genress listed)');
insert into song (version, id, title, artist, genres) values (0,110, 'in faucibus orci luctus et ultrices', 'Betta Wesson', 'Action|Adventure');
